
# on:
#   push:
#     branches:
#       - main

# name: 🚀 Deploy website on push

# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest

#     steps:
#       - name: 🚚 Get latest code
#         uses: actions/checkout@v3

#       # Optional: Build step if using static site generators
#       # - name: 🔧 Build site
#       #   run: npm install && npm run build

#       - name: 📂 Sync files
#         uses: SamKirkland/FTP-Deploy-Action@4.3.3
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           port: 1624
#           # local-dir: ./build   # if you have a build step
#           dangerous-clean-slate: false  # optional


deployment:
  tasks:
    - export DEPLOYPATH=/home/gkzxhmso/repositories/EcomGadgets
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
